project_name: 'mmdbinspect'
version: 2

env:
  - 'GO111MODULE=on'

before:
  hooks:
    - 'go mod tidy'

builds:
  - id: 'mmdbinspect'
    main: './cmd/mmdbinspect/main.go'
    binary: 'mmdbinspect'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    ignore:
      - goos: 'darwin'
        goarch: '386'

archives:
  - id: 'mmdbinspect'
    builds:
      - 'mmdbinspect'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - 'CHANGELOG.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'README.md'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  disable: true

nfpms:
  - id: 'mmdbinspect'
    builds:
      - 'mmdbinspect'
    vendor: 'MaxMind, Inc.'
    homepage: 'https://www.maxmind.com/'
    maintainer: 'MaxMind, Inc. <support@maxmind.com>'
    description: 'Program to look up records for one or more IPs/networks in one or more .mmdb databases.'
    license: 'Apache 2.0 or MIT'
    formats:
      - 'deb'
      - 'rpm'
    bindir: '/usr/bin'
    contents:
      - src: 'CHANGELOG.md'
        dst: '/usr/share/doc/mmdbinspect/CHANGELOG.md'
      - src: 'LICENSE-APACHE'
        dst: '/usr/share/doc/mmdbinspect/LICENSE-APACHE'
      - src: 'LICENSE-MIT'
        dst: '/usr/share/doc/mmdbinspect/LICENSE-MIT'
      - src: 'README.md'
        dst: '/usr/share/doc/mmdbinspect/README.md'

release:
  target_commitish: "{{ .FullCommit }}"
