name: golangci-lint

on:
  push:
  pull_request:
  schedule:
    - cron: "4 10 * * SUN"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
